export const CART_ITEMS ="CART_ITEMS";
export const ORDERED_ITEMS = "ORDERED_ITEMS";
export const NOTIFICATION_WITH_MESSAGE ="NOTIFICATION_WITH_MESSAGE";
export const AMOUNT_PAYABLE ="AMOUNT_PAYABLE";